<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BranchService.Contracts" Version="1.0.8-dev.1" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.11" />
      <PackageReference Include="RecommendationService.Contracts" Version="1.0.2-dev.1" />
      <PackageReference Include="StackExchange.Redis" Version="2.7.27" />
      <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
      <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="9.0.6" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\QAggregationService.Application\QAggregationService.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

</Project>
